services:
  postgres:
    image: postgres:16
    container_name: p0tt0r_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vpn_user
      POSTGRES_PASSWORD: vpn_password
      POSTGRES_DB: vpn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
